### ISSUE TITLE
Fails to install nightly

### ISSUE THREAD

**Issue by jdeut** [NTBBloodbath/nvenv#5]
```
$ nvenv version
nvenv version 1.4.0
```

-------------------------------------------------

The attempt to install nightly fails:

```
$nvenv install nightly
[LOG] Downloading version nightly ...
##O=#    #
[LOG] Installing version nightly ...
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[ERR] Failed to install Nvim.
```

**Comment by NTBBloodbath** [comment]
Hi, haven't used nvenv in a while (didn't had a reason to very recently). Now I'm going to use it again so give me a few hours and I'll dig on it after the work :)

**Comment by NTBBloodbath** [comment]
Right so it's not a nvenv fault. It seems that nightly releases in Neovim sometimes fails, you can take a look at neovim/neovim#15709 for further information.

**Comment by jdeut** [comment]
> Right so it's not a nvenv fault. It seems that nightly releases in Neovim sometimes fails, you can take a look at [neovim/neovim#15709](https://github.com/neovim/neovim/issues/15709) for further information.

Thanks for quickly replying and providing the background information!

I just tried it again and it worked flawlessly.
